In [2]:
import pandas as pd
import numpy as np

In [3]:
data_preprosseced = pd.read_csv('Final_Absenteeism_preprocessed.csv')

In [4]:
data_preprosseced.head()

,Reason1,Reason2,Reason3,Reason4,Month Value,Weekday,Transportation Expense,Distance to Work,Age,Daily Work Load Average(in Minutes),Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,5,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,5,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,6,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,0,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,0,289,36,33,239.554,30,0,2,1,2